use criterion::{black_box, criterion_group, criterion_main, Criterion};
use hibernia::h264::decoder::Decoder;
use hibernia::h264::nal_parser::NalParser;
use std::fs;
use std::io::Cursor;
use std::process::Command;

fn generate_ffmpeg_benchmark_data(path: &str) {
    if std::path::Path::new(path).exists() {
        return;
    }

    println!("Generating benchmark data with ffmpeg...");
    let status = Command::new("ffmpeg")
        .args(&[
            "-y",
            "-f",
            "lavfi",
            "-i",
            "mandelbrot=size=1280x720:rate=30",
            "-t",
            "3",
            "-c:v",
            "libx264",
            "-profile:v",
            "main",
            "-pix_fmt",
            "yuv420p",
            path,
        ])
        .status()
        .expect("Failed to execute ffmpeg");

    assert!(status.success(), "ffmpeg failed to generate benchmark data");
}

fn bench_decoder(b: &mut criterion::Bencher, encoded_video_buffer: &[u8]) {
    b.iter(|| {
        let cursor = Cursor::new(black_box(encoded_video_buffer));
        let nal_parser = NalParser::new(cursor);
        let mut decoder = Decoder::new();

        for nal_result in nal_parser {
            let nal = nal_result.unwrap();
            decoder.decode(&nal).unwrap();
            while let Some(_frame) = decoder.retrieve_picture() {
                // consume frame
            }
        }
        decoder.flush().unwrap();
        while let Some(_frame) = decoder.retrieve_picture() {
            // consume frame
        }
    });
}

pub fn decoding_benchmark(c: &mut Criterion) {
    // Tests Baseline profile, CAVLC entropy coding, and no deblocking filter.
    // This serves as the baseline performance metric for the simplest decoding path.
    let nl2_buffer = fs::read("data/NL2_Sony_H.jsv").expect("can't read NL2_Sony_H.jsv");
    c.bench_function("decode NL2_Sony_H", |b| bench_decoder(b, &nl2_buffer));

    // Tests Main profile, CABAC entropy coding, deblocking filter enabled, and B-slices.
    // This measures a heavy, realistic workload, evaluating CABAC parser efficiency,
    // memory bandwidth during deblocking, and sub-pixel interpolation in B-slices.
    let caba3_buffer = fs::read("data/CABA3_SVA_B.264").expect("can't read CABA3_SVA_B.264");
    c.bench_function("decode CABA3_SVA_B", |b| bench_decoder(b, &caba3_buffer));

    // Tests Constrained Baseline profile, CAVLC entropy coding, and deblocking filter enabled.
    // Short sequence (17 frames) useful for quick iterations while testing deblocking overhead.
    let sva_ba2_buffer = fs::read("data/SVA_BA2_D.264").expect("can't read SVA_BA2_D.264");
    c.bench_function("decode SVA_BA2_D", |b| bench_decoder(b, &sva_ba2_buffer));

    // Tests 720p, Main Profile, 30fps generated by ffmpeg
    // Stresses decoder throughput with higher resolution and longer sequence
    let ffmpeg_720p_path = "target/mandelbrot_720p_main.264";
    let _ = fs::create_dir_all("target");
    generate_ffmpeg_benchmark_data(ffmpeg_720p_path);
    let ffmpeg_720p_buffer =
        fs::read(ffmpeg_720p_path).expect("can't read generated benchmark file");
    let _ = fs::remove_file(ffmpeg_720p_path);

    let mut group = c.benchmark_group("720p_main");
    group.sample_size(10); // Reduce sample size as 720p 90 frames will take longer to decode
    group.bench_function("decode mandelbrot", |b| bench_decoder(b, &ffmpeg_720p_buffer));
    group.finish();
}

criterion_group!(benches, decoding_benchmark);
criterion_main!(benches);
